### ISSUE TITLE
Gulp Build Fails with error TS2786

### ISSUE THREAD

**Issue by IHollen** [OfficeDev/microsoft-teams-apps-champion-management#113]
Hello,

When trying to run gulp build in Node 14.18.2 and Gulp 4.0.2 (referenced in the Deployment-Guide and package.json respectively), we get Type Script errors:
![image](https://user-images.githubusercontent.com/111023132/184030121-34bdd85d-6a5b-4c8c-b1b6-e156d7a8288e.png)
`Error - [tsc] src/webparts/clbHome/components/TOTLandingPage.tsx(XX, YY): error TS2786: '<element>' cannot be used as a JSX component.`

This is after installing a fresh install of Node and has been seen in Windows and Linux environments without any applied customizations.

Is there something we are missing?

**Comment by v-prigunasek** [comment]
Hi @IHollen

Thanks for reporting the issue to us. Can you please try the below items here?

1. Have you already executed these commands, if not please try these and see whether it resolves the error?
npm install gulp yo @microsoft/generator-sharepoint –global
npm install 
npm install -g gulp
gulp trust-dev-cert

2. If you already ran npm install in your solution, can you delete the node modules folder from your solution and try running npm install again?

Let us know if you are still facing the errors.

**Comment by IHollen** [comment]
Hey @v-prigunasek
Thanks very much for the reply.

Those extra dependencies were the fix and we were able to run the build.
Thanks a bunch!
