### ISSUE TITLE
gulp build throws error TS1005: ',' expected.

### ISSUE THREAD

**Issue by AlexFilipovici** [OfficeDev/microsoft-teams-apps-champion-management#27]
```
Build target: DEBUG
[12:05:38] Using gulpfile C:\DEV\microsoft-teams-apps-champion-management\gulpfile.js
[12:05:38] Starting gulp
[12:05:38] Starting 'build'...
[12:05:38] Starting subtask 'configure-sp-build-rig'...
[12:05:38] Finished subtask 'configure-sp-build-rig' after 6.87 ms
[12:05:38] Starting subtask 'pre-copy'...
[12:05:38] Finished subtask 'pre-copy' after 185 ms
[12:05:38] Starting subtask 'copy-static-assets'...
[12:05:38] Starting subtask 'sass'...
[12:05:39] Finished subtask 'sass' after 510 ms
[12:05:39] Starting subtask 'tslint'...
[12:05:40] [tslint] tslint version: 5.12.1
[12:05:41] Starting subtask 'tsc'...
[12:05:41] [tsc] typescript version: 3.3.4000
[12:05:41] Finished subtask 'copy-static-assets' after 2.47 s
[12:05:58] Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3201,70): error TS1005: ',' expected.
[12:05:58] Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3201,81): error TS1005: ',' expected.
[12:05:58] Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3238,64): error TS1005: ',' expected.
[12:05:58] Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3238,75): error TS1005: ',' expected.
[12:05:58] Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3259,82): error TS1005: ',' expected.
[12:05:58] Error - 'tsc' sub task errored after 18 s 
 exited with code 2
[12:05:58] 'build' errored after 20 s
[12:05:58]
[12:05:59] ==================[ Finished ]==================
Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3201,70): error TS1005: ',' expected.
Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3201,81): error TS1005: ',' expected.
Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3238,64): error TS1005: ',' expected.
Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3238,75): error TS1005: ',' expected.
Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3259,71): error TS1005: ',' expected.
Error - [tsc] node_modules/@material-ui/data-grid/dist/data-grid.d.ts(3259,82): error TS1005: ',' expected.
Error - 'tsc' sub task errored after 18 s 
 exited with code 2
[12:05:59] Project clb version:0.0.1
[12:05:59] Build tools version:3.12.1
[12:05:59] Node version:v10.16.0
[12:05:59] Total duration:28 s
[12:05:59] Task errors:7
```

**Comment by AlexFilipovici** [comment]
Worked with node 10.16.3.
